[theme]
base = "dark"
primaryColor = "#8B5CF6"
backgroundColor = "#0A0F1F"
secondaryBackgroundColor = "#ffffffff"
textColor = "#F8FAFC"
font = "sans serif"

[browser]
gatherUsageStats = false

[server]
headless = true

[client]
toolbarMode = "minimal"
showSidebarNavigation = false